# Generated by Django 3.1.4 on 2021-05-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muestra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='NombreMuestra',
            field=models.CharField(default='Nombre Predeterminado Muestra', max_length=50),
        ),
    ]
