# Generated by Django 3.1.7 on 2021-04-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muestra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='horaFechainicio',
            field=models.DateTimeField(),
        ),
    ]
