# Generated by Django 3.1.4 on 2021-05-27 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trampas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Muestra', '0003_muestra_idusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='idTrampas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Trampas.trampas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='muestra',
            name='idUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuario.user'),
            preserve_default=False,
        ),
    ]
