# Generated by Django 3.1.4 on 2021-05-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muestra', '0004_auto_20210526_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='NombreMuestra',
            field=models.CharField(max_length=50),
        ),
    ]
