# Generated by Django 3.1.7 on 2021-06-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muestra', '0005_auto_20210526_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
