# Generated by Django 3.1.4 on 2021-05-21 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trampas', '0001_initial'),
        ('Muestra', '0005_auto_20210521_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='idTrampas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trampas.trampas'),
        ),
    ]
