# Generated by Django 3.1.4 on 2021-07-04 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Trampas', '0003_auto_20210704_1030'),
        ('Muestra', '0006_muestra_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='NombreMuestra',
            field=models.CharField(help_text='Nombre de identificacion de la muestra', max_length=50),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='idTrampas',
            field=models.ForeignKey(help_text='Trampa a la que pertenece la muestra', on_delete=django.db.models.deletion.CASCADE, to='Trampas.trampas'),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='idUsuario',
            field=models.ForeignKey(help_text='Usuario que registro la nueva muestra', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='idtMuestra',
            field=models.BigAutoField(help_text='Numero de identificacion del registro', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Define si el registro esta o no dado de baja en el sistema'),
        ),
    ]
