# Generated by Django 3.1.4 on 2021-08-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Muestra', '0007_auto_20210704_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='etiquetado',
            field=models.CharField(default='Pendiente', help_text='Define el progreso de las fotografias que pertenecen a la muestra', max_length=45),
        ),
    ]
