# Generated by Django 3.1.4 on 2021-05-25 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Estereoscopios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('idcCamaras', models.BigAutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=45)),
                ('foco', models.CharField(max_length=45)),
                ('resolucion', models.CharField(max_length=45)),
                ('idEstereoscopios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estereoscopios.estereoscopio')),
            ],
            options={
                'verbose_name': 'Camara',
                'verbose_name_plural': 'Camaras',
                'db_table': 'cCamaras',
            },
        ),
    ]
