# Generated by Django 3.1.7 on 2021-06-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camaras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
