# Generated by Django 3.1.4 on 2021-07-04 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estereoscopios', '0003_auto_20210704_1030'),
        ('Camaras', '0002_camara_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camara',
            name='foco',
            field=models.CharField(help_text='Foco de la camara', max_length=45),
        ),
        migrations.AlterField(
            model_name='camara',
            name='idEstereoscopios',
            field=models.ForeignKey(help_text='Estereoscopio al que pertenece la Camara', on_delete=django.db.models.deletion.CASCADE, to='Estereoscopios.estereoscopio'),
        ),
        migrations.AlterField(
            model_name='camara',
            name='idcCamaras',
            field=models.BigAutoField(help_text='Numero de identificacion del registro', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='camara',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Define si el registro esta o no dado de baja en el sistema, default: True'),
        ),
        migrations.AlterField(
            model_name='camara',
            name='marca',
            field=models.CharField(help_text='Marca del fabricante de la Camara', max_length=45),
        ),
        migrations.AlterField(
            model_name='camara',
            name='resolucion',
            field=models.CharField(help_text='Resolucion maxima de la Camara', max_length=45),
        ),
    ]
