# Generated by Django 3.1.4 on 2021-07-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estereoscopios', '0002_estereoscopio_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estereoscopio',
            name='caracteristicas',
            field=models.CharField(help_text='Carateristicas o espesificaciones del estereoscopio', max_length=45),
        ),
        migrations.AlterField(
            model_name='estereoscopio',
            name='idcEstereoscopios',
            field=models.BigAutoField(help_text='Numero de identificacion del registro', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estereoscopio',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Define si el registro esta o no dado de baja en el sistema'),
        ),
        migrations.AlterField(
            model_name='estereoscopio',
            name='marca',
            field=models.CharField(help_text='Marca del fabricante del estereoscopio', max_length=45),
        ),
    ]
