# Generated by Django 3.1.7 on 2021-04-29 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Trampas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('idtMuestra', models.BigAutoField(primary_key=True, serialize=False)),
                ('horaFechainicio', models.DateTimeField(auto_now_add=True)),
                ('horaFechaFin', models.DateTimeField()),
                ('idcTrampas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Trampas.trampas')),
            ],
            options={
                'verbose_name': 'tMuestra',
                'verbose_name_plural': 'tMuestras',
                'db_table': 'tMuestras',
            },
        ),
    ]
