# Generated by Django 3.1.7 on 2021-04-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idcUsuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('horaFechaUltimoAcceso', models.DateTimeField()),
                ('horaFechaCreacion', models.DateTimeField()),
                ('tipoUsuario', models.IntegerField()),
                ('email', models.CharField(max_length=45)),
                ('activo', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'cUsuario',
            },
        ),
    ]
