# Generated by Django 3.1.7 on 2021-04-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='activo',
            field=models.CharField(max_length=45),
        ),
    ]
