# Generated by Django 3.1.4 on 2021-06-17 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0005_auto_20210614_2136'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
