# Generated by Django 3.1.4 on 2021-06-17 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0006_auto_20210616_2040'),
        ('Usuario', '0006_auto_20210616_2111'),
    ]

    operations = [
    ]
