# Generated by Django 3.1.7 on 2021-04-29 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Camaras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('idFotografias', models.BigAutoField(primary_key=True, serialize=False)),
                ('horaFecha', models.DateTimeField()),
                ('zoom', models.CharField(max_length=45)),
                ('resolucion', models.CharField(max_length=45)),
                ('idCamara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Camaras.camara')),
            ],
            options={
                'verbose_name': 'Fotografia',
                'verbose_name_plural': 'Fotografias',
                'db_table': 'fotografias',
            },
        ),
    ]
