# Generated by Django 3.1.4 on 2021-05-26 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Muestra', '0002_muestra_nombremuestra'),
        ('Fotografias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='idMuestra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Muestra.muestra'),
            preserve_default=False,
        ),
    ]
