# Generated by Django 3.1.4 on 2021-05-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fotografias', '0002_fotografia_filefoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='horaFecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
