# Generated by Django 3.1.4 on 2021-05-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fotografias', '0003_auto_20210510_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='fileFoto',
            field=models.ImageField(upload_to='Label_Studio_Data/media/upload/'),
        ),
    ]
