# Generated by Django 3.1.4 on 2021-08-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fotografias', '0004_auto_20210704_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='etiquetado',
            field=models.CharField(
                default='Pendiente', help_text="Estado de Etiquetado de la fotografia ('Pendiente' o 'Finalizado')", max_length=45),
        ),
    ]
