# Generated by Django 3.1.4 on 2021-05-25 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Especies', '0001_initial'),
        ('Muestra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesMuestra',
            fields=[
                ('idtDetallesMuestra', models.BigAutoField(primary_key=True, serialize=False)),
                ('horaFecha', models.DateTimeField()),
                ('observaciones', models.CharField(max_length=45)),
                ('cantidad', models.IntegerField()),
                ('idEspecie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Especies.especie')),
                ('idMuestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Muestra.muestra')),
            ],
            options={
                'verbose_name': 'Detalles Muestra',
                'verbose_name_plural': 'Detalles Muestras',
                'db_table': 'tDetallesMuestra',
            },
        ),
    ]
