# Generated by Django 3.1.7 on 2021-04-29 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0002_auto_20210429_1922'),
        ('Muestra', '0003_auto_20210429_1836'),
        ('Especies', '0001_initial'),
        ('Fotografias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesMuestra',
            fields=[
                ('idtDetallesMuestra', models.BigAutoField(primary_key=True, serialize=False)),
                ('horaFecha', models.DateTimeField()),
                ('observaciones', models.CharField(max_length=45)),
                ('cantidad', models.IntegerField()),
                ('idEspecie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Especies.especie')),
                ('idMuestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Muestra.muestra')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario')),
                ('idfotografias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fotografias.fotografia')),
            ],
            options={
                'verbose_name': 'Detalles Muestra',
                'verbose_name_plural': 'Detalles Muestras',
                'db_table': 'tDetallesMuestra',
            },
        ),
    ]
