# Generated by Django 3.2.2 on 2021-06-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetallesMuestra', '0004_alter_detallesmuestra_horafecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesmuestra',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='detallesmuestra',
            name='horaFecha',
            field=models.DateTimeField(),
        ),
    ]
