# Generated by Django 3.1.4 on 2021-06-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetallesMuestra', '0005_auto_20210611_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesmuestra',
            name='horaFecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
