# Generated by Django 3.2.2 on 2021-06-18 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DetallesMuestra', '0006_auto_20210615_1944'),
        ('DetallesMuestra', '0006_auto_20210616_1802'),
    ]

    operations = [
    ]
