# Generated by Django 3.1.4 on 2021-07-04 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Especies', '0003_auto_20210704_1030'),
        ('Muestra', '0007_auto_20210704_1030'),
        ('DetallesMuestra', '0007_merge_0006_auto_20210615_1944_0006_auto_20210616_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesmuestra',
            name='cantidad',
            field=models.IntegerField(help_text='Cantidad de insectos detectados en la muestra'),
        ),
        migrations.AlterField(
            model_name='detallesmuestra',
            name='horaFecha',
            field=models.DateTimeField(auto_now_add=True, help_text='Hora en la que se registro la Muestra'),
        ),
        migrations.AlterField(
            model_name='detallesmuestra',
            name='idEspecie',
            field=models.ForeignKey(help_text='Especies encontradas en la muestra', on_delete=django.db.models.deletion.CASCADE, to='Especies.especie'),
        ),
        migrations.AlterField(
            model_name='detallesmuestra',
            name='idMuestra',
            field=models.ForeignKey(help_text='Muestra a la que pertenecen estos detalles', on_delete=django.db.models.deletion.CASCADE, to='Muestra.muestra'),
        ),
        migrations.AlterField(
            model_name='detallesmuestra',
            name='idtDetallesMuestra',
            field=models.BigAutoField(help_text='Numero de identificacion del registro', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detallesmuestra',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Define si el registro esta o no dado de baja en el sistema'),
        ),
        migrations.AlterField(
            model_name='detallesmuestra',
            name='observaciones',
            field=models.CharField(help_text='Observaciones del empleado sobre la muestra', max_length=45),
        ),
    ]
