# Generated by Django 3.1.4 on 2021-08-01 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Muestra', '0007_auto_20210704_1030'),
        ('DetallesMuestra', '0008_auto_20210704_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesmuestra',
            name='idMuestra',
            field=models.OneToOneField(help_text='Muestra a la que pertenecen estos detalles', on_delete=django.db.models.deletion.CASCADE, to='Muestra.muestra'),
        ),
    ]
