# Generated by Django 3.1.7 on 2021-04-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('idcEspecie', models.BigAutoField(primary_key=True, serialize=False)),
                ('especie', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
                'db_table': 'cEspecies',
            },
        ),
    ]
