# Generated by Django 3.1.4 on 2021-07-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Especies', '0002_especie_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='especie',
            field=models.CharField(help_text='Nombre de la especie', max_length=45),
        ),
        migrations.AlterField(
            model_name='especie',
            name='idcEspecie',
            field=models.BigAutoField(help_text='Numero de identificacion del registro', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='especie',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Define si el registro esta o no dado de baja en el sistema'),
        ),
    ]
