# Generated by Django 3.1.4 on 2021-05-25 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Especies', '0001_initial'),
        ('DetallesMuestra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiquetado',
            fields=[
                ('idEtiquetado', models.BigAutoField(primary_key=True, serialize=False)),
                ('hora_fecha', models.DateTimeField()),
                ('poligono', models.CharField(max_length=45)),
                ('idDetallesMuestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DetallesMuestra.detallesmuestra')),
                ('id_especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Especies.especie')),
            ],
            options={
                'verbose_name': 'Etiquetado',
                'verbose_name_plural': 'Etiquetados',
                'db_table': 'etiquetado',
            },
        ),
    ]
