# Generated by Django 3.1.7 on 2021-06-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etiquetado', '0002_etiquetado_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquetado',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
