# Generated by Django 3.1.4 on 2021-07-04 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Especies', '0003_auto_20210704_1030'),
        ('DetallesMuestra', '0008_auto_20210704_1030'),
        ('Etiquetado', '0003_etiquetado_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiquetado',
            name='hora_fecha',
            field=models.DateTimeField(help_text='Hora y fecha en la que se realizo el etiquetado'),
        ),
        migrations.AlterField(
            model_name='etiquetado',
            name='idDetallesMuestra',
            field=models.ForeignKey(help_text='Muestra a la que pertenece el etiquetado', on_delete=django.db.models.deletion.CASCADE, to='DetallesMuestra.detallesmuestra'),
        ),
        migrations.AlterField(
            model_name='etiquetado',
            name='idEtiquetado',
            field=models.BigAutoField(help_text='Numero de identificacion del registro', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etiquetado',
            name='id_especie',
            field=models.ForeignKey(help_text='Especies observadas en la fotografia', on_delete=django.db.models.deletion.CASCADE, to='Especies.especie'),
        ),
        migrations.AlterField(
            model_name='etiquetado',
            name='id_usuario',
            field=models.ForeignKey(help_text='Usuario al que pertenece el registro', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='etiquetado',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Define si el registro esta o no dado de baja en el sistema'),
        ),
        migrations.AlterField(
            model_name='etiquetado',
            name='poligono',
            field=models.CharField(help_text='Coordenadas que conforman el poligono', max_length=45),
        ),
    ]
