use SIRMAT_DB;
INSERT INTO cespecies (idcEspecie, especie, is_active)
VALUES 
(1, 'Hemiptera|Aphididae|Áfidos', true),
(2, 'Hemiptera|Aphididae|Toxoptera citricida', true),
(3, 'Hemiptera|Aleyrodidae|Aleurocanthus woglumii', true),
(4, 'Hemiptera|Aleyrodidae|Bemisia tabaci', true),
(5, 'Hemiptera|Aleyrodidae|Trialeurodes abutiloneus', true),
(6, 'Hemiptera|Aleyrodidae|Trialeurodes vaporariorum', true),
(7, 'Hemiptera|Psylidae|Diaphorina citri', true),
(8, 'Hemiptera|Chinches y mas', true),
(9, 'Hemiptera|Cicadellidae|Bucephalogonia xanthopis', true),
(10,'Hemiptera|Cicadellidae|Dilobopterus costalimai,', true),
(11, 'Hemiptera|Cicadellidae|Acragonia citrina', true),
(12, 'Hemiptera|Cicadellidae|Acrogonia virescens', true),
(13, 'Hemiptera|Cicadellidae|Ferrariana trivittata', true),
(14, 'Hemiptera|Cicadellidae|Homalodisca ignorata', true),
(15, 'Hemiptera|Cicadellidae|Macugonalia leucomelas', true),
(16, 'Hemiptera|Cicadellidae|Parathona gratiosa', true),
(17, 'Hemiptera|Cicadellidae|Plesiommata corniculata', true),
(18, 'Hemiptera|Cicadellidae|Sonesimia grossa', true),
(19, 'Hemiptera|Cicadellidae|Oncometopia fascialis', true),
(20, 'Coleóptera|Curculionidae|Xyleborus glabratus', true),
(21, 'Coleóptera|Curculionidae|Euwallacea sp', true),
(22, 'Coleóptera|Curculionidae|Xyleborus affinis', true),
(23, 'Coleóptera|Curculionidae|Xyleborus bispinatus', true),
(24, 'Coleóptera|-|Escarabajos', true),
(25, 'Diptera|-|Moscas', true),
(26, 'Diptera|-|Moscos', true),
(27, 'Diptera|Chironomidae|-|', true),
(28, 'Diptera|-|spp', true),
(29, 'Hymenoptera|-|-|', true),
(30, 'Thysanoptera|Tripidae|Thrips palmi', true),
(31, 'Lepidoptera|-|palomillas', true),
(32, 'Collembola|-|colémbolos', true),
(33, 'Arachnida|-|Arachnidos', true),
(34, 'Otros Artropodos|-|-|', true);