# Generated by Django 3.1.4 on 2021-07-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trampas', '0002_trampas_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trampas',
            name='coordenadas',
            field=models.CharField(help_text='Coordenadas en las que se encuentra la trampa', max_length=45),
        ),
        migrations.AlterField(
            model_name='trampas',
            name='direccion',
            field=models.CharField(help_text='Direccion en la que se encuentra la trampa', max_length=45),
        ),
        migrations.AlterField(
            model_name='trampas',
            name='idcTrampas',
            field=models.BigAutoField(help_text='Numero de identificacion del registro', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trampas',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Define si el registro esta o no dado de baja en el sistema'),
        ),
        migrations.AlterField(
            model_name='trampas',
            name='nombre',
            field=models.CharField(help_text='Nombre de la trampa', max_length=45),
        ),
    ]
